update developer lab to include kn func
RedHatGov/serverless-workshop-dashboard pull request #24
Opened 2021-03-24 21:06 UTC by jkeam

2021-03-24 23:19 UTC, dudash commented
Looks good - but 2 questions.
1 - should we break func stuff out into a separate lab? Like 1.5? Just asking, seems like it be fine either way.
2 - do we have to force them to create quay.io account? That seems a bit complicated for a developer. And if the answer is yes, maybe we have them do that before the workshop starts in like a setup lab so as not to muddy the waters in the dev labs...

2021-03-24 23:42 UTC, jkeam commented
> Looks good - but 2 questions.
> 1 - should we break func stuff out into a separate lab? Like 1.5? Just asking, seems like it be fine either way.
> 2 - do we have to force them to create quay.io account? That seems a bit complicated for a developer. And if the answer is yes, maybe we have them do that before the workshop starts in like a setup lab so as not to muddy the waters in the dev labs...

For `1`, ya I thought about that too and seems like both approaches make sense.  I'm ok with either and don't feel passionate either way.

And for `2` every tutorial I've seen requires you to have access to an image repository.  I was actually digging around in the source code for `kn func` and looks like it's an unavoidable step when deploying. https://github.com/boson-project/func/blob/923c788f4a21ec7c109388105ec9b513d9511a48/cmd/deploy.go#L107

2021-03-25 16:26 UTC, theckang commented
I feel like I'm turning in the "homeroom police" so apologies :)

`docker` and `podman` are not in the homeroom image.  So users won't be able to login to their registries.  `kn func build` will fail too since it will look for a docker runtime for build.
![Screen Shot 2021-03-25 at 11 23 57 AM](https://user-images.githubusercontent.com/10468378/112507411-9b7b7880-8d5c-11eb-9a80-d35154f6a102.png)

Not sure how I feel - do you think the extra effort required (adding podman to our Dockerfile, making sure our workshop participants sign up for quay in advance) is worth it to showcase `kn func`?

2021-03-25 16:31 UTC, theckang requested changes

2021-03-25 16:31 UTC, theckang commented on workshop/content/lab1.4_developer.md
> +```shell
Just curious why we made this change.

2021-03-25 16:31 UTC, theckang commented on workshop/content/lab1.4_developer.md
> +There is one caveat to the following section, specifically the deployment section below.  You will need and be logged into an image repository like http://quay.io or http://hub.docker.com.  If you ar
We need to add `podman` to our Docker image.  We should probably make this run command something they could execute.

```execute
podman login quay.io`
```

(assuming they do this in homeroom)

2021-03-25 16:31 UTC, theckang commented on workshop/content/lab1.4_developer.md
> +```
add execute flag

(or shell?)

2021-03-25 17:14 UTC, jkeam commented on workshop/content/lab1.4_developer.md
> +```shell
`execute` didn't seem valid as per the languages supported by the Github Markdown Syntax highlighter https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

2021-03-25 17:22 UTC, jkeam commented
> I feel like I'm turning in the "homeroom police" so apologies :)
> 
> `docker` and `podman` are not in the homeroom image. So users won't be able to login to their registries. `kn func build` will fail too since it will look for a docker runtime for build.
> ![Screen Shot 2021-03-25 at 11 23 57 AM](https://user-images.githubusercontent.com/10468378/112507411-9b7b7880-8d5c-11eb-9a80-d35154f6a102.png)
> 
> Not sure how I feel - do you think the extra effort required (adding podman to our Dockerfile, making sure our workshop participants sign up for quay in advance) is worth it to showcase `kn func`?
> 
> Update: Actually, the more I think about it, this might be much harder to do. This would require docker in docker which we probably want to avoid.

Def a great point.  I'm ok with dropping this for now?  Maybe we include a  "you can also check this thing kn func out, read more about it here"

2021-03-25 20:49 UTC, jkeam commented
> > Looks good - but 2 questions.
> > 1 - should we break func stuff out into a separate lab? Like 1.5? Just asking, seems like it be fine either way.
> > 2 - do we have to force them to create quay.io account? That seems a bit complicated for a developer. And if the answer is yes, maybe we have them do that before the workshop starts in like a setup lab so as not to muddy the waters in the dev labs...
> 
> For `1`, ya I thought about that too and seems like both approaches make sense. I'm ok with either and don't feel passionate either way.
> 
> And for `2` every tutorial I've seen requires you to have access to an image repository. I was actually digging around in the source code for `kn func` and looks like it's an unavoidable step when deploying. https://github.com/boson-project/func/blob/923c788f4a21ec7c109388105ec9b513d9511a48/cmd/deploy.go#L107

Moved instructions to beginning of workshop.

2021-03-25 20:50 UTC, jkeam commented
Going to close this PR as per the discussion here but leaving this branch open in case we ever want to revisit this and use some of the content that I've written.

2021-03-25 20:50 UTC, closed without merging